[Variables]
; --- API & BEHAVIOR ---
Host=123.456.78.90
Port=8372
Token=TOKEN FROM ANDROID APP
; --- This should be loaded from the API, but for simplicity, just set it here aswell. ---
Goal=3000
Increment=250

; --- VISUALS ---
Width=360
Height=90
Padding=2
BarHeight=6
BarWidth= #Width# - 50
BarRadius=4
BarBackgroundColor=175,235,255,20

FontColor=185,230,255
FontName=Gravity Light
FontSize=28
FontSizeSmall=15
