name: Android CI
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    name: Generate App APK
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Bundle 'debug' with Gradle
      run: ./gradlew assembleDebug

    - name: List output folder
      run: ls -la mobile/build/outputs/apk/debug

    - name: Sign APK
      id: sign_apk
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: mobile/build/outputs/apk/debug
        signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
        alias: ${{ secrets.SIGNING_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"


    - run: echo "Build status report=${{ job.status }}."

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }} release

    - name: Upload Release APK
      id: upload_release_asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.sign_apk.outputs.signedReleaseFile }}
        asset_name: ${{ github.event.repository.name }}.apk
        asset_content_type: application/zip
    - run: echo "Upload returned with status=${{ job.status }}."